#
language: java
jdk: oraclejdk11
dist: trusty
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
branches:
  only:
    - develop
    - master
install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script: ./.travis.sh
