# This builds develop and deploys a snapshot to our repository.
# Will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Develop - Build and Deploy Snapshot

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # When parent-2:1.7 is active, -P ensureSnapshots will do a sanity check of the version number
      # We try several times since unfortunately there are sporadic startup problems in the integration tests :-(
      run: |
        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 1st run success ) || \
        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 2nd run success ) || \
        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 3rd run success )

    - name: Sanitycheck version before deploying
      run: |
        echo "Version: "
        mvn -s .github/settings-istrepo.xml help:evaluate -Dexpression=project.version -q -DforceStdout
        mvn -s .github/settings-istrepo.xml help:evaluate -Dexpression=project.version -q -DforceStdout | egrep -- '-SNAPSHOT$' > /dev/null || exit 1
        # unfortunately, this would require a snapshot parent if just called from the command line, so we cannot use it: :-(
        # mvn org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce -Drules=requireSnapshotVersion

    - name: Deploy with Maven
      # We don't do docker pushes as we don't currently (as of 4/22) have an automatic solution for multi architecture builds
      # Compare also https://github.com/actions/virtual-environments/issues/2187 (M1 support for github actions)
      run: mvn -s .github/settings-istrepo.xml -Ddocker.skip.push=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -P develop -B deploy
      env:
        NEXUS_BUILD_USER: ${{ secrets.NEXUS_BUILD_USER }}
        NEXUS_BUILD_PASSWD: ${{ secrets.NEXUS_BUILD_PASSWD }}
