# Sanity check for pull requests - just checks that it compiles.
# Will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Pullrequest - Sanitycheck
run-name: Pullrequest - Sanitycheck on ${{ github.ref_name }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Dump event context for debugging
        continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit messge has a (
        run: |
          echo '${{ github.event_name }} for ${{ github.ref_type }} ${{ github.ref_name }} or ${{ github.event.ref }}'
          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
          echo 'github.event:'
          echo '${{ toJSON(github.event) }}'

      - name: Dump github context
        continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit message has a (
        run: |
          echo '${{ toJSON(github) }}'

      - name: Check of secrets
        continue-on-error: true
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          GPG_OWNERTRUST: ${{ secrets.DOCKERHUB_PASSWD }}
        run: |
          echo $DOCKERHUB_USER | wc
          echo $DOCKERHUB_USER | md5sum
          echo $DOCKERHUB_PASSWD | wc
          echo $DOCKERHUB_PASSWD | md5sum
          echo '${{ toJSON(secrets) }}'

      - name: uname
        continue-on-error: true
        run: |
            uname -a
