# simply starts the launchpad with filesystem based JCR for testing it after a maven build.
# usage e.g.:
# mvn clean install; docker-compose up --force-recreate -V --abort-on-container-exit
# or with start.sh (incl. automatic removal)
# Remove everything e.g. with
# docker-compose down --rmi local -v --remove-orphans

version: "3.7"

services:
  sling:
    image: composum/slingstarter:${DOCKER_IMAGE_TAG}
    container_name: composum-slingstarter
    volumes:
      - "./target/run/logs:/opt/sling/launcher/logs"
      - "./target/run/fileinstall:/opt/sling/fileinstall-user"
      - "./target/run/features:/opt/sling/features-user"
    ports:
      - "8080:8080"
      - "18080:18080"
      - "28080:28080"
